version: '3.8'

services:
  db:
    image: postgres:15
    container_name: notes_db
    environment:
      POSTGRES_DB: notes_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: notes_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: notes_app
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: notes_frontend
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  pgdata: